"""feat(db): AI 분석 정확도 추적 필드 추가

Revision ID: 0bfff577b35d
Revises: a4b9c2d6e8f1
Create Date: 2026-04-04 22:31:00.926362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfff577b35d'
down_revision: Union[str, Sequence[str], None] = 'a4b9c2d6e8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis_logs', sa.Column('accuracy_label', sa.String(), nullable=True))
    op.add_column('ai_analysis_logs', sa.Column('actual_price_diff_pct', sa.Float(), nullable=True))
    op.add_column('ai_analysis_logs', sa.Column('accuracy_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analysis_logs', 'accuracy_checked_at')
    op.drop_column('ai_analysis_logs', 'actual_price_diff_pct')
    op.drop_column('ai_analysis_logs', 'accuracy_label')
    # ### end Alembic commands ###
