"""Claude Code 역할 파일 생성기.

harness/agents.toml(역할·모델·effort·허용 경로) + AGENTS.md(공통 규칙) + harness/roles/<role>.md(역할 본문)
→ .claude/agents/<role>.md

    python scripts/harness.py render          # 생성·갱신
    python scripts/harness.py render --check  # 원본과 일치하는지만 검사 (drift면 exit 1)

생성물은 직접 편집하지 않는다. 원본을 고치고 render를 다시 돌린다.
Codex 병행 시 agents.toml에 codex_model을 추가하고 이 파일에 .codex 출력을 덧붙인다.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "harness" / "agents.toml"
COMMON = ROOT / "AGENTS.md"
ROLES_DIR = ROOT / "harness" / "roles"
OUTPUT_DIR = ROOT / ".claude" / "agents"
MARKER = "Generated by scripts/harness.py"
READ_ONLY_TOOLS = ("Read", "Glob", "Grep")
WRITE_TOOLS = READ_ONLY_TOOLS + ("Edit", "Write", "Bash")
REQUIRED_FIELDS = {"description", "claude_model", "effort", "read_only", "allowed_paths"}


class HarnessError(RuntimeError):
    """원본 설정이 잘못됐거나 생성 대상이 아닌 파일이 자리에 있을 때."""


def _read(path: Path) -> str:
    if not path.is_file():
        raise HarnessError(f"원본 파일이 없습니다: {path.relative_to(ROOT).as_posix()}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def generated() -> dict[str, str]:
    """역할별 생성물을 {저장소 상대 경로: 내용}으로 반환한다."""
    config = tomllib.loads(_read(CONFIG))
    roles = config.get("roles") or {}
    if not roles:
        raise HarnessError("agents.toml에 [roles.*]가 없습니다.")
    common = _read(COMMON)
    outputs: dict[str, str] = {}
    for name, role in roles.items():
        missing = REQUIRED_FIELDS - set(role)
        if missing:
            raise HarnessError(f"roles.{name}에 필드가 없습니다: {', '.join(sorted(missing))}")
        body = _read(ROLES_DIR / f"{name}.md")
        allowed = ", ".join(role["allowed_paths"]) or "없음 (읽기 전용)"
        prompt = f"{common}\n{body}\n허용 경로 후보: {allowed}\n"
        tools = READ_ONLY_TOOLS if role["read_only"] else WRITE_TOOLS
        source = json.dumps(role, sort_keys=True, ensure_ascii=False) + prompt
        digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
        frontmatter = "\n".join(
            [
                "---",
                f"name: {name}",
                f"description: {json.dumps(role['description'], ensure_ascii=False)}",
                f"model: {role['claude_model']}",
                f"effort: {role['effort']}",
                f"tools: {', '.join(tools)}",
                "---",
            ]
        )
        outputs[f".claude/agents/{name}.md"] = (
            f"{frontmatter}\n<!-- {MARKER}; source_sha256={digest} -->\n\n{prompt}"
        )
    return outputs


def render(check: bool) -> int:
    outputs = generated()
    drift: list[str] = []
    for rel, text in outputs.items():
        path = ROOT / rel
        if not path.exists():
            drift.append(f"{rel} (없음)")
            continue
        current = path.read_text(encoding="utf-8")
        if MARKER not in current:
            raise HarnessError(f"생성 대상이 아닌 파일이 자리에 있습니다(마커 없음): {rel}")
        if current != text:
            drift.append(f"{rel} (변경)")
    stale = [
        path
        for path in OUTPUT_DIR.glob("*.md")
        if MARKER in path.read_text(encoding="utf-8")
        and path.relative_to(ROOT).as_posix() not in outputs
    ]
    drift.extend(f"{path.relative_to(ROOT).as_posix()} (원본 없음)" for path in stale)
    if check:
        if drift:
            print("render --check 실패: " + ", ".join(drift))
            return 1
        print(f"render --check OK: {len(outputs)}개 일치")
        return 0
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for rel, text in outputs.items():
        (ROOT / rel).write_text(text, encoding="utf-8", newline="\n")
    for path in stale:
        path.unlink()
    print(f"render 완료: {len(outputs)}개 생성, 변경 {len(drift)}개")
    return 0


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Claude Code 역할 파일 생성기")
    subcommands = parser.add_subparsers(dest="command", required=True)
    render_parser = subcommands.add_parser("render", help="역할 파일 생성 또는 drift 검사")
    render_parser.add_argument("--check", action="store_true", help="생성하지 않고 일치만 검사")
    args = parser.parse_args(argv)
    try:
        return render(check=args.check)
    except HarnessError as exc:
        print(f"harness 오류: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
